version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: xdebug-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: docker/php-fpm
      container_name: xdebug-php-fpm
      working_dir: /application
      environment:
        PHP_IDE_CONFIG: "serverName=my.local"
        XDEBUG_CONFIG: "idekey=PHPSTORM"
      volumes:
        - .:/application

